spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=10s

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

blog:
  api:
    kakao:
      key: KakaoAK a36654d1ff77f6d5fb7633b57dfb6761
      baseUrl: https://dapi.kakao.com/v2/search/blog
    naver:
      key: 4vB2eXBXrQ
      baseUrl: https://openapi.naver.com/v1/search/blog.json
      client: kK6vszWKsvdJWhhGmfyq

swagger:
  api:
    name: Blog Search Api Application
    version: 1.0.0
    description: 블로그 검색 Api 애플리케이션입니다.