spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/searchblog
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

web:
  server: http://localhost:8922

server:
  address: 127.0.0.1
  port: 4261

blog:
  api:
    kakao:
      key: KakaoAK a36654d1ff77f6d5fb7633b57dfb6761
      baseUrl: https://dapi.kakao.com/v2/search/blog
    naver:
      key: 4vB2eXBXrQ
      baseUrl: https://openapi.naver.com/v1/search/blog.json
      client: kK6vszWKsvdJWhhGmfyq