spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/searchblog
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

blog.api.kakao.key: a36654d1ff77f6d5fb7633b57dfb6761
blog.api.kakao.baseUrl: https://dapi.kakao.com/v2/search/blog
blog.api.naver.client: kK6vszWKsvdJWhhGmfyq
blog.api.naver.key: 4vB2eXBXrQ