spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
  properties:
      hibernate:
        show_sql: true
        format_sql: true
  redis:
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

server:
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json
    min-response-size: 1024
  servlet:
    context-path: /api

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details:always
  metrics:
    export:
      prometheus:
        enabled:true

blog:
  api:
    kakao:
      key: KakaoAK a36654d1ff77f6d5fb7633b57dfb6761
      baseUrl: https://dapi.kakao.com/v2/search/blog
    naver:
      key: 4vB2eXBXrQ
      baseUrl: https://openapi.naver.com/v1/search/blog.json
      client: kK6vszWKsvdJWhhGmfyq

swagger:
  api:
    name: Blog Search Api
    version: 1.0.0
    description: 블로그 검색 Api 애플리케이션입니다.

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8